module.exports = {
	"type": "all",
	"env": "dev",
	"table": "ipmi_sensor",
	"frequency": 1000,
	"sensType": ["Ambient Temp",
		"Exhaust Temp",
		"System Power",
		"PSU1 Power",
		"PSU2 Power",
		"Fan 1",
		"Fan 2",
		"Fan 3",
		"Fan 4",
		"Fan 5",
		"Fan 6",
		"CPU FAULT",
		"PSU FAULT",
		"PSU Redundancy",
		"CPU Usage",
		"System 3.3V",
		"AUX 3.3V",
		"PCH 1.05V",
		"PCH 1.5V",
		"System 12V",
		"System 5V",
		"AUX 1.5V",
		"AUX 1.26V",
		"CPU1 VR",
		"CPU2 VR",
		"DIMM AB VR",
		"DIMM CD VR",
		"DIMM EF VR",
		"DIMM GH VR",
		"DIMM AB 0.6V",
		"DIMM CD 0.6V",
		"DIMM EF 0.6V",
		"DIMM GH 0.6V",
		"Power On Hours"]
};